// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.furkqn.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializecreateRoomPayload")
public inline fun createRoomPayload(block: com.furkqn.music.listentogether.proto.CreateRoomPayloadKt.Dsl.() -> kotlin.Unit): com.furkqn.music.listentogether.proto.Listentogether.CreateRoomPayload =
  com.furkqn.music.listentogether.proto.CreateRoomPayloadKt.Dsl._create(com.furkqn.music.listentogether.proto.Listentogether.CreateRoomPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.CreateRoomPayload`
 */
public object CreateRoomPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.furkqn.music.listentogether.proto.Listentogether.CreateRoomPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.furkqn.music.listentogether.proto.Listentogether.CreateRoomPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.furkqn.music.listentogether.proto.Listentogether.CreateRoomPayload = _builder.build()

    /**
     * `string username = 1;`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * `string username = 1;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.furkqn.music.listentogether.proto.Listentogether.CreateRoomPayload.copy(block: `com.furkqn.music.listentogether.proto`.CreateRoomPayloadKt.Dsl.() -> kotlin.Unit): com.furkqn.music.listentogether.proto.Listentogether.CreateRoomPayload =
  `com.furkqn.music.listentogether.proto`.CreateRoomPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

